.Dd $Mdocdate: May 20 2018 $
.Dt REGGAE_SHELL 1
.Os
.Sh NAME
.Nm reggae-shell
.Nd shell provisioner for CBSD jails
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
.Pp
A service with shell provisioner consists of:
.Bl -bullet
.It
\fBMakefile\fR - configured for use with shell
.It
\fBplaybook\fR - containing dummy provision.sh to start with
.El
.Pp
When ran with this configuration, reggae will first mount playbook directory on
/root/shell inside jail. To do actual provisioning, Reggae will run
\fB/root/shell/provision.sh\fR.
.Sh EXAMPLES
.Pp
Quickest way to get basic service provisioned with shell is:
.Pp
.Dl mkdir myservice
.Dl cd myservice
.Dl reggae init shell
.Dl make
.Sh SEE ALSO
.Xr reggae-provision 1
.Sh AUTHORS
Goran Mekić <meka@tilda.center>
