.Dd $Mdocdate: May 20 2018 $
.Dt REGGAE 1
.Os
.Sh NAME
.Nm reggae
.Nd \fBREG\fRister \fBG\fRlobaly \fBA\fRccess \fBEv\fRerywhere is a package
which helps in common DevOps tasks
.Sh SYNOPSIS
.Nm reggae <command>
.Sh DESCRIPTION
.Pp
\fBReggae\fR is an open source package which relays on base \fBFreeBSD\fR
and/or \fBCBSD\fR to provide lower level management for jails and virtual
machines.
.Pp
If you have ever used Vagrant or Docker Compose, Reggae is best described as an
alternative to those. It enables you easy development inside jail while code
editing is done on the host. It makes transition from development to production
easier by using provisioners. It makes host clean of all requirements of
development and puts them inside jail which is easily stopped, started,
provisioned, and destroyed.
.Pp
To initialize Reggae, first edit /usr/local/etc/reggae.conf and add:
.Pp
.Dl PROJECTS_DIR=/usr/home/me/repos
.Pp
It will set directory to be shared with virtual machines, like directory
containing your projects. If you don't need such a directory, you can set it to
/var/empty.
.Pp
.Dl PROJECTS_DIR=/var/empty
.Pp
If you want to run Reggae with base jails, no need to do any other edits, but
if you'd like to use \fBCBSD\fR as the backend, you need to add
.Pp
.Dl BACKEND=cbsd
.Pp
run the following as root:
.Pp
.Dl reggae host-init
.Dl # service pflog restart
.Dl # service pf restart
.Dl reggae backend-init
.Dl reggae network-init
.Pp
PF is initialized only if /etc/pf.conf doesn't exist already. In those cases PF
services should be restarted.
.Pp
Through config file in /usr/local/etc/reggae.conf you can change values for
anything Reggae is using. Ater \fBreggae network-init\fR, you'll get jail
containing DHCP and DNS. They are used to lease IPs to jails and virtual
machines and to register all resources in DNS so that you can use FQDN instead
of IP addresses. This jail IP is used in /etc/resolvconf.conf if host has
dynamic IP on egress, so that changes of network parameters are passed to the
appropriate jail. Also, host will use DNS jail IP in /etc/resolv.conf. In
short, it enables you to not remember jail IPs when you have to use them,
but use <jail name>.<domain> to reference them.
.Sh SEE ALSO
.Xr reggae-project 1
.Xr reggae-provision 1
.Sh BUGS
Report bugs to https://github.com/cbsd/reggae/issues.
.Sh AUTHORS
Goran Mekić <meka@tilda.center>
