.TH "REGGAE-SERVICE" "1" "12 November 2017" "reggae-service" ""

.SH NAME
reggae-service \- use a single jail to run set of processes

.SH SYNOPSIS
\fBservice.mk\fR

.SH "DESCRIPTION"
.PP
Running make will invoke make up and if it is the first time you run it, make
provision will also be executed.

Supported make targets for service are:
 - destroy
 - devel
 - exec
 - export
 - login
 - provision
 - setup
 - up

.SH EXAMPLES
Easiest way to configure a service is Makefile as following:

 SERVICE = myservice
 REGGAE_PATH = /usr/local/share/reggae

 .include <${REGGAE_PATH}/mk/service.mk>


.SH "ADDITIONAL INFORMATION"
See \fBreggae(1)\fR, \fBreggae-project(1)\fR and \fBreggae-ansible(1)\fR for
more info.



