.Dd $Mdocdate: May 20 2018 $
.Dt REGGAE_ANSIBLE 1
.Os
.Sh NAME
.Nm reggae-ansible
.Nd Ansible provisioner for CBSD jails
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
.Pp
A service with ansible provisioner consists of:
.Bl -bullet
.It
\fBMakefile\fR - configured for use with Ansible
.It
\fBplaybook\fR - containing group_vars, inventory and roles directories as placeholders for files generated on the fly, but can be used to configure your playbook
.It
\fBrequirements.yml\fR - list of requirements, with only one initially. All requirements from this file are downloaded from Ansible Galaxy
templates/site.yml.tpl - this file should be edited to add/remove roles, playbooks, etc.
.El
.Pp
When ran with this configuration, reggae will first check if ansible executable
is available on  the host, and if it isn't, it will run \fBpkg install ansible\fR.
If you use Python's virtual environments, for example, you can avoid having
ansible available to everyone on the system.
.Sh EXAMPLES
.Pp
Quickest way to get basic service provisioned with Ansible is:
.Pp
.Dl mkdir myservice
.Dl cd myservice
.Dl reggae init ansible
.Dl make
.Sh SEE ALSO
.Xr reggae-provision 1
.Sh AUTHORS
Goran Mekić <meka@tilda.center>
