.Dd $Mdocdate: May 20 2018 $
.Dt REGGAE_PROJECT 1
.Os
.Sh NAME
.Nm reggae-project
.Nd project provisioner for CBSD jails
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
.Pp
A project consists of:
.Bl -bullet
.It
\fBMakefile\fR - configured for use with project
.El
.Pp
One project can contain many services, and that's going to be shown in the
generated Makefile. The SERVICES variable in it will be commented but populated
with example services. All services when downloaded will be in
services/<service> directory.
.Pp
You can run \fBmake <target>\fR on the project:
.Bl -bullet -offset indent -compact
.It
destroy
.It
devel
.It
fetch
.It
init
.It
login service=<service>
.It
provision
.It
setup
.It
up
.El
.Pp
Special note for the devel target: your repo must have bin/devel.sh which be
ran on the host. All project targets can be suffixed with service=<service>
but in the above list only those which require a service are explicitely
mentioned. If the service is passed as an argument, the target will be
executed only on that service/jail.
.Sh EXAMPLES
.Pp
Quickest way to get basic project is:
.Pp
.Dl mkdir myproject
.Dl cd myproject
.Dl reggae init-project
.Sh SEE ALSO
.Xr reggae-service 1
.Xr reggae-provision 1
.Sh AUTHORS
Goran Mekić <meka@tilda.center>

