.Dd $Mdocdate: May 20 2018 $
.Dt REGGAE_REGISTER 1
.Os
.Sh NAME
.Nm reggae-register
.Nd register provisioner for CBSD jails
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
.Pp
Every jail will be registered to:
.Bl -bullet -offset indent
.It
\fBresolver\fR - jailed DNS used by Reggae
.It
\fBPF\fR - firewall of choice for Reggae
.El
.Sh SEE ALSO
.Xr reggae 1
.Sh AUTHORS
Goran Mekić <meka@tilda.center>

