.TH "REGGAE-ANSIBLE" "1" "12 November 2017" "reggae-ansible" ""

.SH NAME
reggae-ansible \- initialize and setup host for use with reggae

.SH SYNOPSIS
\fBansible.mk\fR

.SH "DESCRIPTION"
.PP
Reggae will run \fBdo_provision\fR target if defined, and that's how \fBansible.mk\fR inserts additional targets.

.SH EXAMPLES
If you include ansible.mk, Reggae will run provision on first invocation of
\fBmake up\fR (or just make). If you want to repeat the provisioning, you have
to explicitely run \fBmake provision\fR. Following is a minimal \fBMakefile\fR which
will provision a jail with ansible:

 SERVICE = myservice
 REGGAE_PATH = /usr/local/share/reggae
 CUSTOM_TEMPLATES = templates

 .include <${REGGAE_PATH}/mk/ansible.mk>
 .include <${REGGAE_PATH}/mk/service.mk>


Reggae will expect this hierarchy:

  playbook/
  inventory/
  group_vars/
  roles/
    myservice/
      tasks/
        main.yml
  templates/
    site.yml.tpl


Example of simple ansible tasks from \fBmain.yml\fR:

 ---
 - name: stop sendmail
   service:
     name: sendmail
     state: stopped


In \fBtemplates\fR you need to have at least \fBsite.yml.tpl\fR:

 ---
 - name: SERVICE provisioning
   hosts: SERVICE
   roles:
     - myservice


You need to install ansible on the host running provisioning. Typing \fBmake\fR
will create \fBmyservice\fR CBSD jail and stop sendmail in it.

.SH "ADDITIONAL INFORMATION"
See \fBreggae(1)\fR for more info.

