.TH "REGGAE-INIT" "1" "12 November 2017" "reggae-init" ""

.SH NAME
reggae-init \- initialize and setup host for use with reggae

.SH SYNOPSIS
\fBreggae\fR init

.SH "DESCRIPTION"
.PP
This command will set up \fBCBSD\fR, bridge1 and lo1 for it's use.

.SH "ADDITIONAL INFORMATION"
See \fBreggae(1)\fR for more info.
