.Dd $Mdocdate: May 20 2018 $
.Dt REGGAE_CHEF 1
.Os
.Sh NAME
.Nm reggae-chef
.Nd chef provisioner for CBSD jails
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
.Pp
A service with chef provisioner consists of:
.Bl -bullet
.It
\fBMakefile\fR - configured for use with chef
.It
\fBplaybook\fR - containing cookbooks/core/recipes/default.rb dummy script
.El
.Pp
When ran with this configuration, reggae will first check if chef executable
is available, and if it isn't, it will run \fBpkg install -y chef\fR inside
jail. Then it will mount playbook directory on /root/chef inside jail. To do
actual provisioning, Reggae uses \fBchef-client --local-mode\fR.
.Sh EXAMPLES
.Pp
Quickest way to get basic service provisioned with Chef is:
.Pp
.Dl mkdir myservice
.Dl cd myservice
.Dl reggae init chef
.Dl make
.Sh SEE ALSO
.Xr reggae-provision 1
.Sh AUTHORS
Goran Mekić <meka@tilda.center>
