.Dd $Mdocdate: May 20 2018 $
.Dt REGGAE_SALT 1
.Os
.Sh NAME
.Nm reggae-salt
.Nd salt provisioner for CBSD jails
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
.Pp
A service with salt provisioner consists of:
.Bl -bullet
.It
\fBMakefile\fR - configured for use with salt
.It
\fBplaybook\fR - containing top.sls and core.sls playbooks
.El
.Pp
When ran with this configuration, reggae will first check if salt executable is
available, and if it isn't, it will run \fBpkg install -y py36-salt\fR inside
jail. Then it will mount playbook directory on /usr/local/etc/salt/states inside
jail. To do actual provisioning, Reggae uses \fBsalt-call --local state.apply\fR.
.Sh EXAMPLES
.Pp
Quickest way to get basic service provisioned with salt is:
.Pp
.Dl mkdir myservice
.Dl cd myservice
.Dl reggae init salt
.Dl make
.Sh SEE ALSO
.Xr reggae-provision 1
.Sh AUTHORS
Goran Mekić <meka@tilda.center>
