.TH "REGGAE-REGISTER" "1" "12 November 2017" "reggae-register" ""

.SH NAME
reggae-register \- register and deregister jails in consul

.SH SYNOPSIS
\fBreggae\fR register <register|deregister>

.SH "DESCRIPTION"
.PP
This is a hook which is invoked by CBSD when starting and stopping jail with \fBregister\fR or \fBderegister\fR as it's argument. It expects \fBjname\fR and \fBip4_addr\fR environemnt variables to be set.


.SH "ADDITIONAL INFORMATION"
See \fBreggae(1)\fR for more info.
