#!/bin/sh

TEMP_FILE=`mktemp`
CBSD_WORKDIR=`sysrc -n cbsd_workdir`

resolvconf -u
echo "forwarders {" >"${TEMP_FILE}"
for resolver in `awk '/^nameserver/{print $2}' /tmp/resolv.conf`; do
    echo -e "\t${resolver};" >>"${TEMP_FILE}"
done
echo "};" >>"${TEMP_FILE}"

chown bind:bind "${TEMP_FILE}"
rm -f "${CBSD_WORKDIR}/jails-data/resolver-data/usr/local/etc/namedb/forwarders.conf"
mv "${TEMP_FILE}" "${CBSD_WORKDIR}/jails-data/resolver-data/usr/local/etc/namedb/forwarders.conf"

if [ "${1}" != "nohup" ]; then
    /usr/local/bin/cbsd jexec jname=resolver service named restart
fi
