#!/bin/sh

if [ -f "/usr/local/etc/reggae.conf" ]; then
    . "/usr/local/etc/reggae.conf"
fi

. "/usr/local/share/reggae/scripts/default.conf"

TEMP_FILE=`mktemp`
CBSD_WORKDIR=`sysrc -n cbsd_workdir`
EGRESS=`netstat -rn | awk '/^default/{print $4}'`
EGRESS_CONFIG=`sysrc -n ifconfig_${EGRESS}`
DHCP_CONFIG=`echo ${EGRESS_CONFIG} | grep -io dhcp`
STATIC=NO


if [ -z "${DHCP_CONFIG}" ]; then
    STATIC=YES
fi

if [ "${STATIC}" = "NO" ]; then
  resolvconf -u
else
  cp /etc/resolv.conf /tmp
  echo "nameserver ${RESOLVER_IP}" >/etc/resolv.conf
fi

echo "forwarders {" >"${TEMP_FILE}"
for resolver in `awk '/^nameserver/{print $2}' /tmp/resolv.conf`; do
  if [ "${RESOLVER_IP}" != "${resolver}" ]; then
    echo -e "\t${resolver};" >>"${TEMP_FILE}"
  fi
done
echo "};" >>"${TEMP_FILE}"

chown bind:bind "${TEMP_FILE}"
rm -f "${CBSD_WORKDIR}/jails-data/resolver-data/usr/local/etc/namedb/forwarders.conf"
mv "${TEMP_FILE}" "${CBSD_WORKDIR}/jails-data/resolver-data/usr/local/etc/namedb/forwarders.conf"

if [ "${1}" != "nohup" ]; then
  /usr/local/bin/cbsd jexec jname=resolver service named restart
fi
